apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: angular-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-backend
  template:
    metadata:
      labels:
        app: angular-backend
    spec:
      containers:
      - name: angular-backend
        image: anushree602/angular-backend:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: com-backend-app
spec:
  selector:
    app: angular-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
